fixtures:
  repositories:
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
    wget: git://github.com/maestrodev/puppet-wget.git
    epel: git://github.com/stahnma/puppet-module-epel.git
  symlinks:
    riemann: "#{source_dir}"
