name 'garethr-riemann'
version '0.1.0'

author 'garethr'
license 'Apache License, Version 2.0'
project_page 'https://github.com/garethr/garethr-riemann'
summary 'Module to manage the Riemann monitoring tool'
dependency 'maestrodev/wget'
dependency 'puppetlabs/stdlib', '~3.2.0'
dependency 'stahnma/epel', '>=0.0.3'
