name          'garethr-riemann'
version       '0.2.1'
author        'garethr'
license       'Apache License, Version 2.0'
summary       'Module to manage the Riemann monitoring tool'
project_page  'https://github.com/garethr/garethr-riemann'
dependency    'maestrodev/wget'
dependency    'puppetlabs/gcc'
dependency    'puppetlabs/stdlib'
